# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5c35985fb2e26a210f931c4b6a92c87"
name = "Retner SmartPush Live"
application_url = "https://retner-smart-push.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://retner-smart-push.vercel.app/auth/callback", "https://retner-smart-push.vercel.app/auth/shopify/callback", "https://retner-smart-push.vercel.app/api/auth/callback" ]

[app_proxy]
url = "https://retner-smart-push.vercel.app/apps/push"
subpath = "push"
prefix = "apps"
